# Generated by Django 4.0.3 on 2022-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0002_remove_crag_slug_remove_route_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crag',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
