# Generated by Django 4.0.3 on 2022-04-02 20:48

import crags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0003_alter_crag_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='crag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=crags.models.upload_to, verbose_name='Image'),
        ),
    ]
