# Generated by Django 4.0.3 on 2022-03-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_tries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='current_seats',
            field=models.IntegerField(default=0),
        ),
    ]
