# Generated by Django 4.0.3 on 2022-03-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0003_alter_crag_created_on'),
        ('events', '0003_alter_event_current_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crags.sector'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
