# Generated by Django 4.0.3 on 2022-03-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
