# Generated by Django 4.0.3 on 2022-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0002_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
