# Generated by Django 4.0.3 on 2022-04-03 11:32

import climbers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbers', '0005_remove_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=climbers.models.upload_to, verbose_name='Image'),
        ),
    ]
